plugins { id 'com.android.application' }

android { namespace 'com.exammaker.app'; compileSdk 34
    defaultConfig { applicationId 'com.exammaker.app'; minSdk 24; targetSdk 34; versionCode 10; versionName '2.1.1-ocr-regex-fix' }
    androidResources { noCompress 'pdf' }
}

dependencies {
    implementation 'com.itextpdf:itext7-core:7.2.5'
    implementation 'cz.adaptech.tesseract4android:tesseract4android:4.8.0'
}
