package com.exammaker.app;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.pdf.PdfRenderer;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;

public class TemplateEditorActivity extends Activity {
 private TemplateFieldEditorView editor; private TextView status; private int index; private Bitmap page;
 @Override public void onCreate(Bundle b){super.onCreate(b);index=getIntent().getIntExtra("templateIndex",0);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);status=new TextView(this);status.setText("در حال رندر و OCR فارسی…");status.setPadding(20,18,20,18);status.setTextSize(16);root.addView(status);editor=new TemplateFieldEditorView(this);root.addView(editor,new LinearLayout.LayoutParams(-1,0,1));LinearLayout buttons=new LinearLayout(this);Button reset=new Button(this);reset.setText("اسکن مجدد");Button save=new Button(this);save.setText("ذخیره و ورود مشخصات");buttons.addView(reset,new LinearLayout.LayoutParams(0,60,1));buttons.addView(save,new LinearLayout.LayoutParams(0,60,1));root.addView(buttons);setContentView(root);reset.setOnClickListener(v->scan());save.setOnClickListener(v->saveAndContinue());scan();}
 private void scan(){status.setText("در حال تحلیل هندسه و اجرای OCR فارسی…");new Thread(()->{try{Bitmap rendered=render();AdvancedTemplateScanner.Result geometry=AdvancedTemplateScanner.analyze(rendered);PersianOcrEngine.OcrResult ocr;try(PersianOcrEngine engine=new PersianOcrEngine(this)){ocr=engine.recognize(rendered);}page=rendered;runOnUiThread(()->{editor.setPage(rendered);editor.setDetection(geometry);status.setText("OCR: "+ocr.confidence+"٪  |  هندسه: "+Math.round(geometry.confidence*100)+"٪  | کادرها را بکشید؛ دستگیره پایین-چپ تغییر اندازه می‌دهد.");});}catch(Exception e){runOnUiThread(()->status.setText("خطای اسکن: "+e.getMessage()));}}).start();}
 private Bitmap render()throws Exception{String asset=String.format(java.util.Locale.US,"templates/template_%02d.pdf",index+1);File tmp=new File(getCacheDir(),"editor.pdf");try(InputStream in=getAssets().open(asset);FileOutputStream out=new FileOutputStream(tmp)){byte[] buf=new byte[8192];int n;while((n=in.read(buf))>0)out.write(buf,0,n);}ParcelFileDescriptor fd=ParcelFileDescriptor.open(tmp,ParcelFileDescriptor.MODE_READ_ONLY);PdfRenderer renderer=new PdfRenderer(fd);PdfRenderer.Page p=renderer.openPage(0);Bitmap b=Bitmap.createBitmap(1190,1684,Bitmap.Config.ARGB_8888);b.eraseColor(Color.WHITE);p.render(b,null,null,PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);p.close();renderer.close();fd.close();return b;}
 private void saveAndContinue(){try{JSONArray arr=new JSONArray();for(TemplateFieldEditorView.FieldBox f:editor.getBoxes()){JSONObject o=new JSONObject();o.put("id",f.id);o.put("left",f.rect.left);o.put("top",f.rect.top);o.put("right",f.rect.right);o.put("bottom",f.rect.bottom);arr.put(o);}getSharedPreferences("template_profiles",0).edit().putString("template_"+index,arr.toString()).apply();Intent i=new Intent(this,MainActivity.class);i.putExtra("selectedTemplate",index);i.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_NEW_TASK);startActivity(i);finish();}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}}
 @Override protected void onDestroy(){super.onDestroy();if(page!=null&&!page.isRecycled())page.recycle();}
}
